### ISSUE TITLE
stapler implements Servlet API 2.5 which is pretty old

### ISSUE THREAD

**Issue by jtnord** [stapler/stapler#114]
Stapler implements only the servlet 2.5 API - yet many applications now use 3.1 (either directly or indirectly_

If you attempt to directly use parts of the 3.1 API on a `StaplerRequest` or `StaplerResponse` then weird/bad things could happen depending on what you get underneath..
I have not observed any issues yet - but if you get a `org.kohsuke.stapler.StaplerResponseWrapper` rather than a `org.kohsuke.stapler.ResponseImpl` then things are liable to blow up. the same probably applies to `StaplerRequest` sub classes.

Apparantly (although no details are confirmed), this is causing some issues seen in the wild on the [Jenkins project](https://issues.jenkins-ci.org/browse/JENKINS-37062?focusedCommentId=298534&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-298534)

**Comment by jglick** [comment]
Care to file a PR for it? IIUC the Jetty bundled in Jenkins implements 3.x so we could use this.
