### ISSUE TITLE
Error used when DataBoundConstructor annotation is present more than once is not descriptive

### ISSUE THREAD

**Issue by MRamonLeon** [stapler/stapler#179]
Recently I've found out that if you have two constructors annotated with `@DataBoundConstrutor` you get this error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] javax.annotation.processing.FilerException: Attempt to reopen a file for path ...... ClassName.stapler
  	at com.sun.tools.javac.processing.JavacFiler.checkFileReopening(JavacFiler.java:535)

```

A most descriptive message would be appreciated.

**Comment by jglick** [comment]
See https://github.com/stapler/stapler/blob/c8c28eb749937ab239d7b7f94c2254340103f67e/core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java#L85.

**Comment by MRamonLeon** [comment]
https://github.com/stapler/stapler/pull/180
