### ISSUE TITLE
IllegalArgumentException on when the setter parameter is of type Object

### ISSUE THREAD

**Issue by nfalco79** [stapler/stapler#181]
The full description of the issue is [here](https://issues.jenkins-ci.org/browse/JENKINS-61438)

In short: RequestImpl instantiate a ChoiceParameterDefinition class and than using reflection lookup a setter `@DataBoundSetter` annotated for "choice" property. It takes the parameter type from method (in this unlikely case Object) and than use apache beanutils to convert the actual value "v1\n2\n3" (String) to Object. Since there are no converter registered for Object it fails

**Comment by jglick** [comment]
[JENKINS-61438](https://issues.jenkins.io/browse/JENKINS-61438)
