### ISSUE TITLE
com.intellij.diagnostic.PluginException - Intellij IDEA Plugin

### ISSUE THREAD

**Issue by M-r-A** [stapler/stapler#247]
Got an error message just after I opened my project with fresh IDE install.

IDE Fatal Errors says:
> Do not request resource from classloader using path with leading slash
> 
> com.intellij.diagnostic.PluginException: /org/kohsuke/stapler/idea/resources/schemas/ant.xsd [Plugin: Stapler plugin for IntelliJ IDEA]
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:504)
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:471)
> 	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
> 	at org.kohsuke.stapler.idea.StaplerApplicationComponent$1.run(StaplerApplicationComponent.java:51)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
> 	at org.kohsuke.stapler.idea.StaplerApplicationComponent.initComponent(StaplerApplicationComponent.java:40)
> 	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:407)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:366)
> 	at com.intellij.idea.ApplicationLoader$startApp$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:136)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
> 	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
> 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:408)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

IDEA version: 2021.2 Beta build 212.4746.2 Released: July 14, 2021
Plugin version: 1.8

https://plugins.jetbrains.com/plugin/1885-stapler-plugin-for-intellij-idea

**Comment by timja** [comment]
Likely fixed in 2.0, but if not fixed please report to https://github.com/jenkinsci/idea-stapler-plugin
