### ISSUE TITLE
@RequirePOST should be mandatory on web methods

### ISSUE THREAD

**Issue by jglick** [stapler/stapler#32]
Since it is common for people to forget to specify `@RequirePOST`, I would suggest that it take a `boolean value() default true;` attribute so that you can use `@RequirePOST(false)` to explicitly indicate that `GET` requests are acceptable on a given web method. (`Processor` would simply ignore the annotation with `!value()`; might require an API addition to `Interceptor` to allow the processor to get the actual annotation.)

Then `RequirePOSTAnnotationProcessor` should check for apparent web methods (whatever `WebMethodAnnotationProcessor` would accept) which lack the annotation, and issue an error, forcing plugin developers to make a decision about each such method.

Alternately, deprecate `@RequirePOST` and make `@WebMethod` mandatory, adding a `boolean requirePOST();` attribute with no default. I tend to prefer this since it makes it much clearer in source code that something is expected to be a web method (and allows tools like IDEs to find all such methods). For binary compatibility, Stapler would need to continue to discover implicit web methods (and handle explicit web methods missing the annotation attribute), but at least the compiler would force them to be marked for newly built plugins. Would need to clarify the status of `getSomething(String)` methods, which `@WebMethod` claims to support yet which do not seem like web methods in the ordinary sense.

**Comment by kohsuke** [comment]
`@WebMethod` is not just for a submission but used for anything where the request handling should be done in Java code. Requiring POST like this is a bad idea IMO.

**Comment by jglick** [comment]
For methods which are intended to be used as `GET` requests, you would write

```java
@WebMethod(name="whatever", requirePost=false)
```

**Comment by kohsuke** [comment]
Now that I've merged #59 I think I captured the intent of this proposal better in #60.
