### ISSUE TITLE
HttpResponse uses platform dependant line terminators.

### ISSUE THREAD

**Issue by jtnord** [stapler/stapler#91]
[`org.kohsuke.stapler.HttpResponses.html(String)`](https://github.com/stapler/stapler/blob/2faa6d34283a32b371d00b2eefd8862da8eda0ad/core/src/main/java/org/kohsuke/stapler/HttpResponses.java#L208) and  [`org.kohsuke.stapler.HttpResponses.plainText(String)`](https://github.com/stapler/stapler/blob/2faa6d34283a32b371d00b2eefd8862da8eda0ad/core/src/main/java/org/kohsuke/stapler/HttpResponses.java#L224) use platform dependant line terminators in the response, yet the unit test assert that response is using Unix style line ends here and here.

Obviously one is wrong as this causes the unit tests to fail on windows - yet I am not sure which is incorrect, the response or the test.

I am thinking it is more likely to be `HttpResponses` but am not 100% convinced.

```
Failed tests:
  DispatcherTest.testArbitraryWebMethodName:104 expected:<I'm index[]
] but was:<I'm index[
>
  DispatcherTest.testIndexDispatchByName:40 expected:<Hello world[]
] but was:<Hello world[
>
  DispatcherTest.testInheritance:188 expected:<abc[]
] but was:<abc[
>
  DispatcherTest.testInterceptorStage:144 expected:<3,5[]
] but was:<3,5[
>
  DispatcherTest.testInterceptorStageContentTypeWithCharset:161 expected:<3,5[]
] but was:<3,5[
>
  DispatcherTest.testPutInheritance:224 expected:<Hello World![]
] but was:<Hello World![
>
  DispatcherTest.testVerbMatch:67->check:79 expected:<Got GET[]
] but was:<Got GET[
>
```

**Comment by jtnord** [comment]
infact thinking about it more, Stapler should not be messing with what you asked it to send...
If I asked it to send "I Am A Fish!" I should expect "I Am A Fish!" not "I Am A Fish!\n"

**Comment by jglick** [comment]
> Stapler should not be messing with what you asked it to send

Ideally true, but that would be incompatible to change now, unless you deprecated the originals and introduced replacements.

I think it should be sending `\n` in all cases, since the newline terminator of the master should be irrelevant to clients. (`\r\n` is correct for HTTP headers, but we are talking here about textual content, parsed at a different layer.)

**Comment by jtnord** [comment]
> Ideally true, but that would be incompatible to change now

Any change is going to break something - but you seem to think breaking windows sites is OK?

I say break it and do the right thing - web site code should behave the same when run on any platform.
